### ISSUE TITLE
Hyphen breaks ampersand

### ISSUE THREAD

**Issue by steakscience** [grzm/jekyll-hyphenate_filter#3]
Hi,

I've done `{{ content | replace: '&amp;amp;', '&amp;' | replace: '-­', '-'}}` but I still encounter this issue.

For example, I have this sentence:
`Take that, you #&*$ed-up abomination of nature.`

Hyphenate will add a hyphen inside the escaped ampersand, which breaks the escape:
![image](https://user-images.githubusercontent.com/2727095/59558568-61296700-901f-11e9-85ea-974bf82f5c83.png)

How would I go about fixing this? Thank you.

**Comment by mslinn** [comment]
I have a similar problem. This plugin escapes HTML entities.

My documentation often uses `&lt;` and `&gt;` to display HTML tags, and `&amp;`.  The entities are rendered 'raw' when this plugin is active.

**Comment by grzm** [comment]
Apologies. This library is no longer actively maintained.
